name: "git-cliff: Changelog Generator"
description: "Generate changelog based on your Git history"
inputs:
  args:
    description: "git-cliff arguments"
    required: false
    default: "-v"
outputs:
  changelog:
    description: 'generated changelog'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
branding:
  icon: "triangle"
  color: "orange"
